- name: Restart ser2net
  service: name=ser2net state=restarted

- name: Restart socat on ccu
  service: name=socat-homematic@{{ inventory_hostname }} state=restarted
  delegate_to: "{{ occu_host }}"

- name: Restart HMIPServer on ccu
  service: name=HMIPServer state=restarted
  delegate_to: "{{ occu_host }}"
